### PR TITLE
Revert "format tracebacks with cause (#100)"

### PR DESCRIPTION
**Pull request by dneuhaeuser-zalando**
This reverts commit 1c945209689be023cd4a7d3634ff3148a8e064a3 introduced in PR https://github.com/lightstep/lightstep-tracer-python/pull/100

This fails with `AttributeError: 'str' object has no attribute '__cause__'` in production for us. I'll look more deeply into why this happened later but for now this should fix the bleeding.

### CODE REVIEW

**Comment by dneuhaeuser-zalando** [comment]
FYI @codeboten

**Comment by codeboten** [comment]
@dneuhaeuser-zalando it looks like the parameters for `format_exception` were reversed. Looking at the documentation here: https://docs.python.org/3.8/library/traceback.html#traceback.format_exception

```
traceback.format_exception(etype, value, tb, limit=None, chain=True)¶
```

I haven't tested this yet, but searching through some python issues, it looks like in python2 the inverted arguments would have worked anyways: https://bugs.python.org/issue17413#msg184146

Either ways I'll take a look at adding some tests around this case!
